package com.brightmd.db.dao;

import com.brightmd.db.mapper.UserMapper;
import com.brightmd.db.model.User;
import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.BindBean;
import org.skife.jdbi.v2.sqlobject.GetGeneratedKeys;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;

@RegisterMapper(UserMapper.class)
public interface UserDao {

    @SqlUpdate("create table user (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,firstname varchar(45),lastname varchar(45),zipcode varchar(45),emailaddress varchar(45),PRIMARY KEY (id))")
    void createUserTable();


    @SqlUpdate("drop table user IF EXISTS")
    void dropUserTable();

    @SqlQuery("select * from user where id = :id")
    User getUserById(@Bind("id") int id);

    @SqlUpdate("insert into user (id, firstName, lastName, zipcode, emailaddress) values (NULL, :firstName, :lastName, :zipcode, :emailaddress)")
    @GetGeneratedKeys()
    int createUser(@BindBean User user);

    @SqlUpdate("update user set firstName = :firstName, lastName =:lastName, zipcode = :zipcode, emailaddress = :emailaddress where id = :id")
    void updateUser(@BindBean User user);


    @SqlUpdate("delete from user where id = :id")
    void deleteUser(@Bind("id") int id);
}
